In [3]:
import tensorflow as tf
print(tf.__version__)


2.14.0


In [ ]:
pip install tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

In [4]:
print("hello world")

hello world


In [5]:
import tensorflow as tf

# Define a constant tensor
hello = tf.constant("Hello, TensorFlow!")

# Create a TensorFlow session
with tf.compat.v1.Session() as sess:
    # Run the session to execute the graph
    result = sess.run(hello)
    print(result.decode())


RuntimeError: The Session graph is empty. Add operations to the graph before calling run().

In [6]:
import tensorflow as tf

# Enable eager execution
tf.compat.v1.enable_eager_execution()

# Define a constant tensor
hello = tf.constant("Hello, TensorFlow!")

# Convert the tensor to a string
result = hello.numpy()

# Print the result
print(result.decode())


Hello, TensorFlow!


In [15]:
result.decode()

'Hello, TensorFlow!'

In [16]:
import torch

# Create a tensor with a single value
tensor_scalar = torch.tensor(3.14)
print(tensor_scalar)

# Create a 1D tensor
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
print(tensor_1d)

# Create a 2D tensor (matrix)
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor_2d)


tensor(3.1400)
tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [10]:
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, TensorFlow!'>

In [18]:
import torch
a = torch.tensor(3.0)
print(a)

tensor(3.)


In [35]:
import torch
b = torch.tensor([3., 4,5,6])
print(b)

tensor([3., 4., 5., 6.])


In [47]:
import torch
c= torch.tensor([[1.,2,3],[2,5,6],[8,3,6]])
print(c)

tensor([[1., 2., 3.],
        [2., 5., 6.],
        [8., 3., 6.]])


In [49]:
c.shape

torch.Size([3, 3])

In [28]:
type(a)
type(b)
type(c)

torch.Tensor

In [29]:
type(b)


torch.Tensor

In [31]:
type(c)

torch.Tensor

In [36]:
b


tensor([3., 4., 5., 6.])

In [37]:
c = b+10
print(c)

tensor([13., 14., 15., 16.])


In [38]:
d = b*10
d

tensor([30., 40., 50., 60.])

In [39]:
e = b**2
e

tensor([ 9., 16., 25., 36.])

In [40]:
f = b/2
f

tensor([1.5000, 2.0000, 2.5000, 3.0000])

In [66]:
# Tensors with gradient tracking
x = torch.tensor(2.0, requires_grad=True)
y = x**5 + x**5 + 1



# Compute gradients
y.backward()

# Access gradients
print("Gradient of x:", x.grad)


Gradient of x: tensor(160.)


In [72]:
a = torch.tensor(3., requires_grad=True)
y = a**5 + a**5 +1
y.backward()
print(a.grad)

tensor(810.)


In [78]:
b = torch.tensor(4., requires_grad=True)
c = b**3 + b**3 +1
c.backward()
print(b.grad)

tensor(96.)


In [79]:
import torch.nn as nn

# Define a simple neural network class
class SimpleNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNN, self).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        return x

# Instantiate the neural network
input_size = 10
hidden_size = 5
output_size = 2

model = SimpleNN(input_size, hidden_size, output_size)
print(model)


SimpleNN(
  (layer1): Linear(in_features=10, out_features=5, bias=True)
  (relu): ReLU()
  (layer2): Linear(in_features=5, out_features=2, bias=True)
)
